### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'check_password'

### ISSUE THREAD

**Issue by nicksellen** [yunity/karrot-backend#416] opened 2017-10-28 18:01 UTC
https://sentry.io/foodsaving-worldwide/backend/issues/351121366/

```
AttributeError: 'NoneType' object has no attribute 'check_password'
(12 additional frame(s) were not displayed)
...
  File "rest_framework/views.py", line 486, in dispatch
    response = handler(request, *args, **kwargs)
  File "foodsaving/userauth/api.py", line 33, in create
    if serializer.is_valid():
  File "rest_framework/serializers.py", line 237, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "rest_framework/serializers.py", line 435, in run_validation
    value = self.validate(value)
  File "foodsaving/userauth/serializers.py", line 11, in validate
    user = authenticate(**credentials)

AttributeError: 'NoneType' object has no attribute 'check_password'
```

**Comment by tiltec** [comment] 2017-10-29 06:21
I remember seeing this error in Sentry a while ago and I couldn't find the cause. Maybe need to dig deeper…

**Comment by nicksellen** [comment] 2017-10-31 08:26
Can reproduce:
- visit https://alpha.foodsaving.world/
- use an email address that you know is not registered already, and any password
- observe a 500 error

(If you use an email address that is registered, but incorrect password, it gives a correct validation error)

**Comment by tiltec** [comment] 2017-10-31 08:40
Fixed in https://github.com/yunity/karrot-backend/commit/c16e01cb4b2c6852939d533bb9e292e93e36da92

**Closed by tiltec** 2017-10-31 08:40 UTC
